name: github-test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "build is started"
          echo "build is completed"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test
        run: |
          echo "test is started"
          echo "test is completed"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy
        run: |
          echo "deploy is started"
          echo "deploy is completed"
       
