name: github-test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Node.js
        run: |
          # Update the package index
          sudo apt-get update
          
          # Install Node.js and npm manually
          # The -y flag is crucial for automation!
          sudo apt-get install -y nodejs npm
          
      - name: Verify versions
        run: |
          node -v
          npm -v
      
