name: github-test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "build is not started"
          echo "build is not completed"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test
        run: |
          echo "test is started"
          echo "test is completed"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy
        run: |
          echo "deploy is started"
          echo "deploy is completed"
       
